# -*- coding: utf-8 -*-
"""Philly_POMP.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fCV35ZsbkjAlNOLDEIwg2fUC0lVYIt0b

# Community infection prevalence estimated by a quasi-mechanistic model using contact tracing samples, community population survey samples, and a particle filter
 @authors: Justin K Sheen

 - Script to incorporate (1) contact tracing and (2) community population survey data in the fitting process of a deterministic SEIR, or SEIR-variant mechanistic model to ultimately make an estimate of the prevalence of infection on a community or population level. For each tested parameter set, we ask how likely it is given time series data. More explicitly at each slice of the time series, we ask how likely this data could have originated from a certain parameter set, and then add up all slices of the time series.
- Observation 1: there is a lot of overlap of what we are viewing from each compartment of the process model (SEIR model) via each of the three methods. After accounting for selection bias, all three methods must agree with one another. If there exists a parameter set that leads to agreement in some results of the testing methods and not others, then it is less likely than one that agrees among all three data sources. So all three of the "testing dynamics" plots at the bottom of the doc must agree.
- Observation 2: we can fit the selection bias that must have occurred to explain our results, and if it extraordinary under some parameter set, then it is probably less likely than one where the selection bias is more reasonable. We can account for this in the observation model of pomp.

# References
- Johndrow et al.: SIR model linked with death model. https://arxiv.org/pdf/2004.02605.pdf
- Kahn et al.: biases in observational serology. https://www.medrxiv.org/content/10.1101/2020.05.02.20088765v1.full.pdf
- King et al.: POMP method to fit data to a compartmental model: https://arxiv.org/pdf/1509.00503.pdf
- Romero-Severson et al.: SEIR models (e.g. fixed or varying transmission) are fit using case count data and death count data using POMP. Country level data. https://www.medrxiv.org/content/10.1101/2020.04.18.20070771v3

# Create process model and observation model
- With full observation model: https://drive.google.com/file/d/1u6YRdLKpKpNNZ4WgCWV0zeolAYPk2fbc/view?usp=sharing
- With simpler observation model: https://drive.google.com/file/d/1PQ--y3GrMD_6U5Dk1VPrW09bWG7HEpEq/view?usp=sharing

## Import libraries and set seed
"""

if(!require(pomp)){install.packages("pomp", repos="http://cran.rstudio.com/", dependencies=TRUE)}
if(!require(doParallel)){install.packages("doParallel", repos="http://R-Forge.R-project.org", dependencies=TRUE)}
if(!require(doRNG)){install.packages("doRNG", repos="http://cran.rstudio.com/", dependencies=TRUE)}
if(!require(dplyr)){install.packages("dplyr", repos="http://cran.rstudio.com/", dependencies=TRUE)}
if(!require(boot)){install.packages("boot", repos="http://cran.rstudio.com/", dependencies=TRUE)}
if(!require(extraDistr)){install.packages("extraDistr", repos="http://cran.rstudio.com/", dependencies=TRUE)}
library(pomp)
library(doParallel)
library(doRNG)
library(dplyr)
library(boot)
library(extraDistr)

set.seed(1)

"""## Define the process model of the epidemic"""

sir_step <- function (S, E, I, H, R, D, N, 
                      logit_Beta, logit_phi, logit_psi, 
                      logit_gamma_one, logit_gamma_two, logit_theta_one, logit_theta_two,
                      delta.t, 
                      ...) {
  # Random draws from S compartment --------------------------------------------
  dN_SE <- rbinom(n=1, size=S, prob=1 - exp(-inv.logit(logit_Beta) * I * delta.t))

  # Random draws from E compartment --------------------------------------------
  dN_EI <- rbinom(n=1, size=E, prob=inv.logit(logit_phi) * delta.t)

  # Random draws from I compartment --------------------------------------------
  dN_IH <- rbinom(n=1, size=I, prob=inv.logit(logit_psi) * delta.t)
  dN_IR <- ifelse((I - dN_IH) == 0, 
                  0, 
                  rbinom(n=1, size=(I - dN_IH), prob=inv.logit(logit_gamma_one) * delta.t))
  dN_ID <- ifelse((I - dN_IH - dN_IR) == 0, 
                  0, 
                  rbinom(n=1, size=(I - dN_IH - dN_IR), prob=inv.logit(logit_theta_one) * delta.t))
  
  # Random draws from H compartment --------------------------------------------
  dN_HR <- rbinom(n=1, size=H, prob=inv.logit(logit_gamma_two) * delta.t)
  dN_HD <- ifelse((H - dN_HR) == 0, 
                  0,
                  rbinom(n=1, size=(H - dN_HR), prob=inv.logit(logit_theta_two) * delta.t))

  # Change all compartments of process model -----------------------------------
  S <- S - dN_SE
  E <- E + dN_SE - dN_EI
  I <- I + dN_EI - dN_IH - dN_IR - dN_ID
  H <- H + dN_IH - dN_HR - dN_HD
  R <- R + dN_IR + dN_HR
  D <- D + dN_ID + dN_HD

  # Add tests to stop simulation if there is an error --------------------------
  if (S + E + I + H + R + D != N) { stop("Sum of compartments != N.") }
  
  # Assign new values for each compartment -------------------------------------
  c(S = S, E = E, I = I, H = H, R = R, D = D)
}

"""## Define initial conditions of the epidemic"""

sir_init <- function (N, logit_eta, ...) {
  c(S = round(N * (1 - inv.logit(logit_eta))),
    E = 0,
    I = round(N * inv.logit(logit_eta)),
    H = 0,
    R = 0, 
    D = 0)
}

"""## Rough ideas and notes for observation method link to process model
- Potentially understand if there is an agreement between the different data sources, accounting for w_i_j. Should look more at how to make a statistical argument using method of two or three list comparison with list dependence correction for estimation of undocumented homicides. https://hrdag.org/wp-content/uploads/2015/07/2015-hrdag-estimating-undoc-homicides.pdf
- Observed difference between our model and Romero-Severson. Romero-Severson, for each person going from E to I, will be assigned to either counted and died, counted and did not die, not counted and died, not counted and did not die right off the bat. Will then show up in the observation model eventually (somewhat a two-layer observation model). Our model, we do not set it up this way. Instead link our observation model directly to the process model with the sampling process (one-layer observation model).
- Observation of Johndrow et al. Johndrow et al. solely observes deaths, and assumes that the deaths arrive via infection fatalities that occurred in the past 14 days or so. Each day, we see some number of deaths from infection fatalities that occurred in the past 14 days or so.
- Aside: need to double check if the idea of accumulation of likelihood is between time slices and captured in the idea of "particles" as well. As well as where to start fitting the data (e.g. correction for forgiving lag).
- Composite priors and likelihoods?

## Define observation model of the epidemic
- Define how we are observing some part of the process model (link to the observation model).
- Selection bias away from an SRS is described by w_i_j, where i corresponds to test method and j to the compartment measured by the method. This eliminates the need for the previously considered detection rate defined as, rho_i_j, where i corresponds to test method and j to the compartment measured by the method and was used when using binomial random variables.
- Currently, observations are not removed from the process model when observed.
"""

rmeas <- function (S, E, I, H, R, D, N,
                   sample_size_RNA, sample_size_Ser,
                   w_RNA_S, w_RNA_R,
                   w_RNA_E, w_RNA_I, w_RNA_H,
                   w_Ser_S, w_Ser_E,
                   w_Ser_I, w_Ser_H, w_Ser_R,
                   logit_prob_Penn_H, logit_prob_Penn_R, logit_prob_Penn_D, 
                   ...) {
  # RT-PCR daily sample --------------------------------------------------------
  ## Take latent sample from weighted population -------------------------------
  latent_sample_RNA <- rmvhyper(nn=1, 
                                n=c(round(S * w_RNA_S), 
                                    round(E * w_RNA_E), 
                                    round(I * w_RNA_I), 
                                    round(H * w_RNA_H), 
                                    round(R * w_RNA_R)),
                                k=sample_size_RNA)
  
  ## Construction of pos. and neg. RNA samples ---------------------------------
  neg_RNA = latent_sample_RNA[,1] + latent_sample_RNA[,5]
  pos_RNA_E = latent_sample_RNA[,2]
  pos_RNA_I = latent_sample_RNA[,3]
  pos_RNA_H = latent_sample_RNA[,4]

  # Serology daily sample ------------------------------------------------------
  ## Take latent sample from weighted population -------------------------------
  latent_sample_Ser <- rmvhyper(nn=1, 
                                n=c(round(S * w_Ser_S), 
                                    round(E * w_Ser_E), 
                                    round(I * w_Ser_I),
                                    round(H * w_Ser_H),
                                    round(R * w_Ser_R)),
                                k=sample_size_Ser)
  
  ## Construction of pos. and neg. serology samples ----------------------------
  neg_Ser = latent_sample_Ser[,1] + latent_sample_Ser[,2]
  pos_Ser_I = latent_sample_Ser[,3]
  pos_Ser_H = latent_sample_Ser[,4]
  pos_Ser_R = latent_sample_Ser[,5]
  
  # Penn EHR daily sample ------------------------------------------------------
  reports_Penn_H = rbinom(n=1, H, inv.logit(logit_prob_Penn_H))
  reports_Penn_R = rbinom(n=1, R, inv.logit(logit_prob_Penn_R))
  reports_Penn_D = rbinom(n=1, D, inv.logit(logit_prob_Penn_D))

  # Return all observations of the epidemic ------------------------------------
  c(neg_RNA=neg_RNA, pos_RNA_E=pos_RNA_E, pos_RNA_I=pos_RNA_I, pos_RNA_H=pos_RNA_H, 
    neg_Ser=neg_Ser, pos_Ser_I=pos_Ser_I, pos_Ser_H=pos_Ser_H, pos_Ser_R=pos_Ser_R,
    reports_Penn_H=reports_Penn_H, reports_Penn_R=reports_Penn_R, reports_Penn_D=reports_Penn_D)
}

"""## Define the likelihood function (inverse of observation model)
- Define the likelihood that an observation is observed from this observation process.
"""

dmeas <- function (S, E, I, H, R, D,
                   sample_size_RNA, sample_size_Ser,
                   w_RNA_S, w_RNA_R,
                   w_RNA_E, w_RNA_I, w_RNA_H,
                   w_Ser_S, w_Ser_E, 
                   w_Ser_I, w_Ser_H, w_Ser_R,
                   logit_prob_Penn_H, logit_prob_Penn_R, logit_prob_Penn_D,
                   neg_RNA, pos_RNA_E, pos_RNA_I, pos_RNA_H, 
                   neg_Ser, pos_Ser_I, pos_Ser_H, pos_Ser_R,
                   reports_Penn_H, reports_Penn_R, reports_Penn_D,
                   log,
                   ...) {
  # RT-PCR log likelihoods based on multivariate hypergeometric function -------
  log_lik_RNA <- dmvhyper(x=c(neg_RNA, 
                              pos_RNA_E, 
                              pos_RNA_I, 
                              pos_RNA_H),
                          n=c(round(S * w_RNA_S) + round(R * w_RNA_R),
                              round(E * w_RNA_E),
                              round(I * w_RNA_I),
                              round(H * w_RNA_H)),
                          k=sample_size_RNA,
                          log=log)

  # Serology log likelihoods based on multivariate hypergeometric function -----
  log_lik_Ser <- dmvhyper(x=c(neg_Ser,
                              pos_Ser_I,
                              pos_Ser_H,
                              pos_Ser_R),
                          n=c(round(S * w_Ser_S) + round(E * w_Ser_E),
                              round(I * w_Ser_I),
                              round(H * w_Ser_H),
                              round(R * w_Ser_R)),
                          k=sample_size_Ser,
                          log=log)

  # Penn EHR likelihoods -------------------------------------------------------
  log_lik_Penn_H <- dbinom(x=reports_Penn_H, size=H, prob=inv.logit(logit_prob_Penn_H), log=log)
  log_lik_Penn_R <- dbinom(x=reports_Penn_R, size=R, prob=inv.logit(logit_prob_Penn_R), log=log)
  log_lik_Penn_D <- dbinom(x=reports_Penn_D, size=D, prob=inv.logit(logit_prob_Penn_D), log=log)

  # Combine the log likelihoods into combined log likelihood -------------------
  combined_log_lik <- log_lik_RNA +
                      log_lik_Ser +
                      log_lik_Penn_H + log_lik_Penn_R + log_lik_Penn_D
  
  # Return combined log likelihood ---------------------------------------------
  combined_log_lik
}

"""# Simulate the process model and observation model
- Objective: gain intuition of types of time series  signals resulting from the observation model we would expect under certain relevant parameter regimes of the process model.

## Simulate
- Process model and observation model are put in a POMP object and then simulated.
"""

# Create data skeleton for pomp ------------------------------------------------
covid_pomp <- as.data.frame(1:90)
covid_pomp <- cbind(covid_pomp, covid_pomp, covid_pomp, covid_pomp, covid_pomp,
                    covid_pomp, covid_pomp, covid_pomp, covid_pomp, covid_pomp,
                    covid_pomp, covid_pomp)
colnames(covid_pomp) <- c("day", "neg_RNA", "pos_RNA_E", "pos_RNA_I", "pos_RNA_H", 
                          "neg_Ser", "pos_Ser_I", "pos_Ser_H", "pos_Ser_R", 
                          "reports_Penn_H", "reports_Penn_R", "reports_Penn_D")

# Prepare pomp object with process model and observation model -----------------
covid_pomp %>%
  pomp(times="day", t0=0,
       rprocess=euler(sir_step, delta.t=1),
       rinit=sir_init,
       dmeasure=dmeas,
       rmeasure=rmeas,
       statenames=c("S", "E", "I", "H", "R", "D"),
       paramnames=c("logit_Beta", "logit_phi", "logit_psi", 
                    "logit_gamma_one", "logit_gamma_two", "logit_theta_one", "logit_theta_two",
                    "logit_eta",
                    "sample_size_RNA", "sample_size_Ser",
                    "w_RNA_S", "w_RNA_R", 
                    "w_RNA_E", "w_RNA_I", "w_RNA_H",
                    "w_Ser_S", "w_Ser_E",
                    "w_Ser_I", "w_Ser_H", "w_Ser_R",
                    "logit_prob_Penn_H", "logit_prob_Penn_R", "logit_prob_Penn_D"),
       params=c(logit_Beta=0, logit_phi=0, logit_psi=0, 
                logit_gamma_one=0, logit_gamma_two=0, 
                logit_theta_one=0, logit_theta_two=0,
                logit_eta=0,
                sample_size_RNA=0, sample_size_Ser=0,
                w_RNA_S=0, w_RNA_R=0, 
                w_RNA_E=0, w_RNA_I=0, w_RNA_H=0,
                w_Ser_S=0, w_Ser_E=0, 
                w_Ser_I=0, w_Ser_H=0, w_Ser_R=0,
                logit_prob_Penn_H=0, logit_prob_Penn_R=0, logit_prob_Penn_D=0,
                N=0)
  ) -> covid_pomp

# Simulate process and observation model using pomp ----------------------------
covid_pomp %>%
  simulate(params=c(logit_Beta=logit(1/10000), logit_phi=logit(1/5), logit_psi=logit(0.033), 
                    logit_gamma_one=logit(0.133), logit_gamma_two=logit(0.125), 
                    logit_theta_one=logit(0.0114), logit_theta_two=logit(0.0228),
                    logit_eta=logit(3/10000),
                    sample_size_RNA=25, sample_size_Ser=50,
                    w_RNA_S=1/100, w_RNA_R=1, 
                    w_RNA_E=1, w_RNA_I=1, w_RNA_H=1,
                    w_Ser_S=1/100, w_Ser_E=1, 
                    w_Ser_I=1, w_Ser_H=1, w_Ser_R=1,
                    logit_prob_Penn_H=logit(0.2), logit_prob_Penn_R=logit(0.01), logit_prob_Penn_D=logit(0.2),
                    N=10000),
            nsim=1, 
            format="data.frame", 
            include.data = TRUE) -> sims

"""## Plot simulation results

### Plot epidemic dynamics
"""

# Plot epidemic dynamics -------------------------------------------------------
for (i in 1:length(unique(sims$.id))) {
        if (as.character(unique(sims$.id)[i] != "data")) {
          sim <- sims[which(sims$.id == unique(sims$.id)[i]),]
          if (i == 2) {
            plot(sim$day, sim$I, ylim=c(0,10000), type="l", col="red",
                 main="Philly COVID-19 dynamics", ylab="# in compartment", xlab="day")
            lines(sim$day, sim$R, col="blue")
            lines(sim$day, sim$S, col="black")
            lines(sim$day, sim$E, col="green")
            lines(sim$day, sim$H, col="yellow")
            lines(sim$day, sim$D, col="purple")
          } else {
            # Need to add code to plot subsequent simulations if more than one
          }
        }
}

"""### Plot testing results"""

# Plot testing dynamics --------------------------------------------------------
for (i in 1:length(unique(sims$.id))) {
        if (as.character(unique(sims$.id)[i] != "data")) {
          sim <- sims[which(sims$.id == unique(sims$.id)[i]),]
          if (i == 2) {
            # RNA data plot ----------------------------------------------------
            RNA_data <- do.call(rbind, list("neg_RNA"=sim$neg_RNA, 
                                            "pos_RNA_E"=sim$pos_RNA_E, 
                                            "pos_RNA_I"=sim$pos_RNA_I, 
                                            "pos_RNA_H"=sim$pos_RNA_H))
            colnames(RNA_data) = as.character(sim$day)
            barplot(RNA_data, 
                    col=c("grey","green","red","blue"), 
                    border="white", 
                    space=0.04, 
                    font.axis=2, 
                    xlab="day",
                    ylab="# tests",
                    main="RNA data",
                    legend=T,
                    args.legend = list(x='bottomright'))

            # Ser data plot ----------------------------------------------------
            Ser_data <- do.call(rbind, list("neg_Ser"=sim$neg_Ser, 
                                            "pos_Ser_I"=sim$pos_Ser_I, 
                                            "pos_Ser_H"=sim$pos_Ser_H, 
                                            "pos_Ser_R"=sim$pos_Ser_R))
            colnames(Ser_data) <- as.character(sim$day)
            barplot(Ser_data, 
                    col=c("grey","red","blue","purple"), 
                    border="white", 
                    space=0.04, 
                    font.axis=2, 
                    xlab="day",
                    ylab="# tests",
                    main="Serology data",
                    legend=T)
                    
            # Penn EHR ---------------------------------------------------------
            EHR_data <- do.call(rbind, list("reports_Penn_H"=sim$reports_Penn_H,
                                            "reports_Penn_R"=sim$reports_Penn_R,
                                            "reports_Penn_D"=sim$reports_Penn_D))
            colnames(EHR_data) <- as.character(sim$day)
            barplot(EHR_data, 
                    col=c("red","blue","black") , 
                    border="white", 
                    font.axis=2, 
                    beside=T,
                    ylim=c(0, max(sim$reports_Penn_H, sim$reports_Penn_R, sim$reports_Penn_D)),
                    legend=rownames(EHR_data), 
                    xlab="day",
                    font.lab=2,
                    args.legend = list(x='topleft'))
          } else {
            # Need to add code to plot subsequent simulations if more than one
          }
        }
}

"""# Fit SEIR model to simulated report data

## State true values of simulation
"""

true_logit_Beta=logit(1/10000) 
true_logit_phi=logit(1/5)
true_logit_psi=logit(0.033)
true_logit_gamma_one=logit(0.133) 
true_logit_gamma_two=logit(0.125) 
true_logit_theta_one=logit(0.0114)
true_logit_theta_two=logit(0.0228)
true_logit_eta=logit(3/10000)
true_w_RNA_S=1
true_w_RNA_R=5
true_w_RNA_E=5
true_w_RNA_I=5
true_w_RNA_H=5
true_w_Ser_S=1
true_w_Ser_E=5
true_w_Ser_I=5
true_w_Ser_H=5
true_w_Ser_R=5
true_logit_prob_Penn_H=logit(0.2)
true_logit_prob_Penn_R=logit(0.01)
true_logit_prob_Penn_D=logit(0.2)

"""## Create a single simulation of reports and tests and save as a .csv"""

covid_pomp %>%
  simulate(params=c(logit_Beta=true_logit_Beta, 
                    logit_phi=true_logit_phi, 
                    logit_psi=true_logit_psi, 
                    logit_gamma_one=true_logit_gamma_one, 
                    logit_gamma_two=true_logit_gamma_two, 
                    logit_theta_one=true_logit_theta_one, 
                    logit_theta_two=true_logit_theta_two,
                    logit_eta=true_logit_eta,
                    sample_size_RNA=25, sample_size_Ser=50,
                    w_RNA_S=true_w_RNA_S, 
                    w_RNA_R=true_w_RNA_R, 
                    w_RNA_E=true_w_RNA_E,
                    w_RNA_I=true_w_RNA_I, 
                    w_RNA_H=true_w_RNA_H,
                    w_Ser_S=true_w_Ser_S, 
                    w_Ser_E=true_w_Ser_E, 
                    w_Ser_I=true_w_Ser_I, 
                    w_Ser_H=true_w_Ser_H, 
                    w_Ser_R=true_w_Ser_R,
                    logit_prob_Penn_H=true_logit_prob_Penn_H,
                    logit_prob_Penn_R=true_logit_prob_Penn_R, 
                    logit_prob_Penn_D=true_logit_prob_Penn_D,
                    N=10000),
            nsim=1,
            format="data.frame", 
            include.data = TRUE) -> sims

write.csv(sims, paste0("~/Philly_Covid/pomp/data/simulated_real/simulated_real.csv"))

"""## Read in simulated report data"""

simulated_infestation <- read.csv(paste0("~/Philly_Covid/pomp/data/simulated_real/simulated_real.csv"))
simulated_infestation <- simulated_infestation[which(simulated_infestation$.id == 1),]
simulated_infestation <- simulated_infestation[,c("day",
                                                  "neg_RNA", "pos_RNA_E", "pos_RNA_I", "pos_RNA_H",
                                                  "neg_Ser", "pos_Ser_I", "pos_Ser_H", "pos_Ser_R",
                                                  "reports_Penn_H", "reports_Penn_R", "reports_Penn_D")]

"""## Create grid, p, of starting points for MCMC
- Pretty good starting points at the moment (will change later).
"""

expand.grid(
  center=1,
  logit_Beta=runif(n=1, max=true_logit_Beta * 0.8, min=true_logit_Beta * 1.2), 
  logit_phi=runif(n=1, max=true_logit_phi * 0.8, min=true_logit_phi * 1.2),
  logit_psi=runif(n=1, max=true_logit_psi * 0.8, min=true_logit_psi * 1.2),
  logit_gamma_one=runif(n=1, max=true_logit_gamma_one * 0.8, min=true_logit_gamma_one * 1.2), 
  logit_gamma_two=runif(n=1, max=true_logit_gamma_two * 0.8, min=true_logit_gamma_two * 1.2), 
  logit_theta_one=runif(n=1, max=true_logit_theta_one * 0.8, min=true_logit_theta_one * 1.2),
  logit_theta_two=runif(n=1, max=true_logit_theta_two * 0.8, min=true_logit_theta_two * 1.2),
  logit_eta=runif(n=1, max=true_logit_eta * 0.8, min=true_logit_eta * 1.2),
  sample_size_RNA=25,
  sample_size_Ser=50,
  w_RNA_S=runif(n=1, min=true_w_RNA_S * 0.5, max=true_w_RNA_S * 1.5),
  w_RNA_R=runif(n=1, min=true_w_RNA_R * 0.5, max=true_w_RNA_R * 1.5),
  w_RNA_E=runif(n=1, min=true_w_RNA_E * 0.5, max=true_w_RNA_E * 1.5),
  w_RNA_I=runif(n=1, min=true_w_RNA_I * 0.5, max=true_w_RNA_I * 1.5),
  w_RNA_H=runif(n=1, min=true_w_RNA_H * 0.5, max=true_w_RNA_H * 1.5),
  w_Ser_S=runif(n=1, min=true_w_Ser_S * 0.5, max=true_w_Ser_S * 1.5),
  w_Ser_E=runif(n=1, min=true_w_Ser_E * 0.5, max=true_w_Ser_E * 1.5),
  w_Ser_I=runif(n=1, min=true_w_Ser_I * 0.5, max=true_w_Ser_I * 1.5),
  w_Ser_H=runif(n=1, min=true_w_Ser_H * 0.5, max=true_w_Ser_H * 1.5),
  w_Ser_R=runif(n=1, min=true_w_Ser_R * 0.5, max=true_w_Ser_R * 1.5),
  logit_prob_Penn_H=runif(n=1, max=true_logit_prob_Penn_H * 0.8, min=true_logit_prob_Penn_H * 1.2),
  logit_prob_Penn_R=runif(n=1, max=true_logit_prob_Penn_R * 0.8, min=true_logit_prob_Penn_R * 1.2),
  logit_prob_Penn_D=runif(n=1, max=true_logit_prob_Penn_D * 0.8, min=true_logit_prob_Penn_D * 1.2),
  N=10000
) -> p

"""## Set up priors for each parameter
- Pretty good priors at the moment (will change later).
"""

hyperparams <- list(min = coef(covid_pomp), max = coef(covid_pomp))
hyperparams$min <- c(logit_Beta=true_logit_Beta * 1.2, 
                     logit_phi=true_logit_phi * 1.2, 
                     logit_psi=true_logit_psi * 1.2, 
                     logit_gamma_one=true_logit_gamma_one * 1.2, 
                     logit_gamma_two=true_logit_gamma_two * 1.2, 
                     logit_theta_one=true_logit_theta_one * 1.2, 
                     logit_theta_two=true_logit_theta_two * 1.2,
                     logit_eta=true_logit_eta * 1.2,
                     w_RNA_S=true_w_RNA_S * 0.5,
                     w_RNA_R=true_w_RNA_R * 0.5, 
                     w_RNA_E=true_w_RNA_E * 0.5, 
                     w_RNA_I=true_w_RNA_I * 0.5, 
                     w_RNA_H=true_w_RNA_H * 0.5,
                     w_Ser_S=true_w_Ser_S * 0.5, 
                     w_Ser_E=true_w_Ser_E * 0.5,
                     w_Ser_I=true_w_Ser_I * 0.5, 
                     w_Ser_H=true_w_Ser_H * 0.5, 
                     w_Ser_R=true_w_Ser_R * 0.5,
                     logit_prob_Penn_H=true_logit_prob_Penn_H * 1.2,
                     logit_prob_Penn_R=true_logit_prob_Penn_R * 1.2, 
                     logit_prob_Penn_D=true_logit_prob_Penn_D * 1.2)
hyperparams$max <- c(logit_Beta=true_logit_Beta * 0.8,
                     logit_phi=true_logit_phi * 0.8, 
                     logit_psi=true_logit_psi * 0.8, 
                     logit_gamma_one=true_logit_gamma_one * 0.8, 
                     logit_gamma_two=true_logit_gamma_two * 0.8, 
                     logit_theta_one=true_logit_theta_one * 0.8, 
                     logit_theta_two=true_logit_theta_two * 0.8,
                     logit_eta=true_logit_eta * 0.8,
                     w_RNA_S=true_w_RNA_S * 1.5, 
                     w_RNA_R=true_w_RNA_R * 1.5, 
                     w_RNA_E=true_w_RNA_E * 1.5, 
                     w_RNA_I=true_w_RNA_I * 1.5, 
                     w_RNA_H=true_w_RNA_H * 1.5,
                     w_Ser_S=true_w_Ser_S * 1.5, 
                     w_Ser_E=true_w_Ser_E * 1.5, 
                     w_Ser_I=true_w_Ser_I * 1.5, 
                     w_Ser_H=true_w_Ser_H * 1.5, 
                     w_Ser_R=true_w_Ser_R * 1.5,
                     logit_prob_Penn_H=true_logit_prob_Penn_H * 0.8,
                     logit_prob_Penn_R=true_logit_prob_Penn_R * 0.8, 
                     logit_prob_Penn_D=true_logit_prob_Penn_D * 0.8)

covid_pomp.dprior <- function (logit_Beta, logit_phi, logit_psi,
                               logit_gamma_one, logit_gamma_two, logit_theta_one, logit_theta_two,
                               logit_eta,
                               sample_size_RNA, sample_size_Ser,
                               w_RNA_S, w_RNA_R, 
                               w_RNA_E, w_RNA_I, w_RNA_H,
                               w_Ser_S, w_Ser_E,
                               w_Ser_I, w_Ser_H, w_Ser_R,
                               logit_prob_Penn_H, logit_prob_Penn_R, logit_prob_Penn_D,
                               N,
                               log,
                               ...) {
  # Get individual log likelihoods ---------------------------------------------
  f_logit_Beta <- dunif(logit_Beta, min=hyperparams$min["logit_Beta"], max=hyperparams$max["logit_Beta"], log=log)
  f_logit_phi <- dunif(logit_phi, min=hyperparams$min["logit_phi"], max=hyperparams$max["logit_phi"], log=log)
  f_logit_psi <- dunif(logit_psi, min=hyperparams$min["logit_psi"], max=hyperparams$max["logit_psi"], log=log)
  f_logit_gamma_one <- dunif(logit_gamma_one, min=hyperparams$min["logit_gamma_one"], max=hyperparams$max["logit_gamma_one"], log=log)
  f_logit_gamma_two <- dunif(logit_gamma_two, min=hyperparams$min["logit_gamma_two"], max=hyperparams$max["logit_gamma_two"], log=log)
  f_logit_theta_one <- dunif(logit_theta_one, min=hyperparams$min["logit_theta_one"], max=hyperparams$max["logit_theta_one"], log=log)
  f_logit_theta_two <- dunif(logit_theta_two, min=hyperparams$min["logit_theta_two"], max=hyperparams$max["logit_theta_two"], log=log)
  f_logit_eta <- dunif(logit_eta, min=hyperparams$min["logit_eta"], max=hyperparams$max["logit_eta"], log=log)
  f_sample_size_RNA <- 0
  f_sample_size_Ser <- 0
  f_w_RNA_S <- dunif(w_RNA_S, min=hyperparams$min["w_RNA_S"], max=hyperparams$max["w_RNA_S"], log=log)
  f_w_RNA_R <- dunif(w_RNA_R, min=hyperparams$min["w_RNA_R"], max=hyperparams$max["w_RNA_R"], log=log)
  f_w_RNA_E <- dunif(w_RNA_E, min=hyperparams$min["w_RNA_E"], max=hyperparams$max["w_RNA_E"], log=log)
  f_w_RNA_I <- dunif(w_RNA_I, min=hyperparams$min["w_RNA_I"], max=hyperparams$max["w_RNA_I"], log=log)
  f_w_RNA_H <- dunif(w_RNA_H, min=hyperparams$min["w_RNA_H"], max=hyperparams$max["w_RNA_H"], log=log)
  f_w_Ser_S <- dunif(w_Ser_S, min=hyperparams$min["w_Ser_S"], max=hyperparams$max["w_Ser_S"], log=log)
  f_w_Ser_E <- dunif(w_Ser_E, min=hyperparams$min["w_Ser_E"], max=hyperparams$max["w_Ser_E"], log=log)
  f_w_Ser_I <- dunif(w_Ser_I, min=hyperparams$min["w_Ser_I"], max=hyperparams$max["w_Ser_I"], log=log)
  f_w_Ser_H <- dunif(w_Ser_H, min=hyperparams$min["w_Ser_H"], max=hyperparams$max["w_Ser_H"], log=log)
  f_w_Ser_R <- dunif(w_Ser_R, min=hyperparams$min["w_Ser_R"], max=hyperparams$max["w_Ser_R"], log=log)
  f_logit_prob_Penn_H <- dunif(logit_prob_Penn_H, min=hyperparams$min["logit_prob_Penn_H"], max=hyperparams$max["logit_prob_Penn_H"], log=log)
  f_logit_prob_Penn_R <- dunif(logit_prob_Penn_R, min=hyperparams$min["logit_prob_Penn_R"], max=hyperparams$max["logit_prob_Penn_R"], log=log)
  f_logit_prob_Penn_D <- dunif(logit_prob_Penn_D, min=hyperparams$min["logit_prob_Penn_D"], max=hyperparams$max["logit_prob_Penn_D"], log=log)
  f_N <- 0

  # Combine log likelihoods ----------------------------------------------------
  f <- sum(f_logit_Beta +
           f_logit_phi +
           f_logit_psi +
           f_logit_gamma_one +
           f_logit_gamma_two +
           f_logit_theta_one +
           f_logit_theta_two +
           f_logit_eta +
           f_sample_size_RNA +
           f_sample_size_Ser +
           f_w_RNA_S +
           f_w_RNA_R +
           f_w_RNA_E +
           f_w_RNA_I +
           f_w_RNA_H +
           f_w_Ser_S +
           f_w_Ser_E +
           f_w_Ser_I +
           f_w_Ser_H +
           f_w_Ser_R +
           f_logit_prob_Penn_H +
           f_logit_prob_Penn_R +
           f_logit_prob_Penn_D +
           f_N)
           
  if (w_RNA_S <= 0 | w_RNA_R <= 0 | w_RNA_E <= 0 | w_RNA_I <= 0 | w_RNA_H <= 0 |
      w_Ser_S <= 0 | w_Ser_E <= 0 | w_Ser_I <= 0 | w_Ser_H <= 0 | w_Ser_R <= 0) {
        0
  } else {
    if (log) f else exp(f)
  }
}

"""## Set up random walk variance for MCMC for each parameter"""

rw.sd <- c(logit_Beta=0.1,
           logit_phi=0.1,
           logit_psi=0.1,
           logit_gamma_one=0.1,
           logit_gamma_two=0.1,
           logit_theta_one=0.1,
           logit_theta_two=0.1,
           logit_eta=0.1,
           sample_size_RNA=0,
           sample_size_Ser=0,
           w_RNA_S=0.02,
           w_RNA_R=0.02,
           w_RNA_E=0.02,
           w_RNA_I=0.02,
           w_RNA_H=0.02,
           w_Ser_S=0.02,
           w_Ser_E=0.02,
           w_Ser_I=0.02,
           w_Ser_H=0.02,
           w_Ser_R=0.02,
           logit_prob_Penn_H=0.1,
           logit_prob_Penn_R=0.1,
           logit_prob_Penn_D=0.1,
           N=0)

"""## Set up parallel computing"""

registerDoParallel()
registerDoRNG(421776444)

"""## Recover best parameters of the SEIR model when fitting simulated report data
- For each parameter combination: get log likelihood using the particle filter. Then assign the log likelihood value to the column "loglik" of the data frame "p."
- Use MCMC and look for convergence later.
"""

foreach (theta=iter(p,"row"),
         .combine=rbind,
         .inorder=FALSE) %dopar% {
           library(pomp)
                 
           simulated_infestation %>%
             pomp(times="day",t0=0,
                  rprocess=euler(sir_step, delta.t=1),
                  rinit=sir_init,
                  dmeasure=dmeas,
                  rmeasure=rmeas,
                  statenames=c("S", "E", "I", "H", "R", "D"),
                  paramnames=c("logit_Beta", "logit_phi", "logit_psi", 
                               "logit_gamma_one", "logit_gamma_two", "logit_theta_one", "logit_theta_two",
                               "logit_eta",
                               "sample_size_RNA", "sample_size_Ser",
                               "w_RNA_S", "w_RNA_R", 
                               "w_RNA_E", "w_RNA_I", "w_RNA_H",
                               "w_Ser_S", "w_Ser_E",
                               "w_Ser_I", "w_Ser_H", "w_Ser_R",
                               "logit_prob_Penn_H", "logit_prob_Penn_R", "logit_prob_Penn_D"),
                  dprior=covid_pomp.dprior,
                  params=theta
             ) -> covid_pomp
                 
           covid_pomp %>% pmcmc(
             start = theta,
             Nmcmc = 5000,
             Np = 100,
             proposal = mvn.diag.rw(rw.sd)
           ) -> pmcmc
                 
           as.data.frame(pmcmc@traces)
                 
           } -> pmcmc_res

write.csv(pmcmc_res, paste0("~/Philly_Covid/pomp/data/parameter_recovery/parameter_recovery.csv"))

# Read in the MCMC results
pmcmc_res <- read.csv(paste0("~/Philly_Covid/pomp/data/parameter_recovery/parameter_recovery.csv"))

# Find parameter set that led to best log likelihood
best_log_lik_param_set <- pmcmc_res[tail(which(pmcmc_res$loglik == max(pmcmc_res$loglik)), 1),]
posterior_logit_Beta=best_log_lik_param_set$logit_Beta
posterior_logit_phi=best_log_lik_param_set$logit_phi
posterior_logit_psi=best_log_lik_param_set$logit_psi
posterior_logit_gamma_one=best_log_lik_param_set$logit_gamma_one
posterior_logit_gamma_two=best_log_lik_param_set$logit_gamma_two
posterior_logit_theta_one=best_log_lik_param_set$logit_theta_one
posterior_logit_theta_two=best_log_lik_param_set$logit_theta_two
posterior_logit_eta=best_log_lik_param_set$logit_eta
posterior_w_RNA_S=best_log_lik_param_set$w_RNA_S
posterior_w_RNA_R=best_log_lik_param_set$w_RNA_R
posterior_w_RNA_E=best_log_lik_param_set$w_RNA_E
posterior_w_RNA_I=best_log_lik_param_set$w_RNA_I
posterior_w_RNA_H=best_log_lik_param_set$w_RNA_H
posterior_w_Ser_S=best_log_lik_param_set$w_Ser_S
posterior_w_Ser_E=best_log_lik_param_set$w_Ser_E
posterior_w_Ser_I=best_log_lik_param_set$w_Ser_I
posterior_w_Ser_H=best_log_lik_param_set$w_Ser_H
posterior_w_Ser_R=best_log_lik_param_set$w_Ser_R
posterior_logit_prob_Penn_H=best_log_lik_param_set$logit_prob_Penn_H
posterior_logit_prob_Penn_R=best_log_lik_param_set$logit_prob_Penn_R
posterior_logit_prob_Penn_D=best_log_lik_param_set$logit_prob_Penn_D

# Prepare pomp object (again) for plotting of posterior
simulated_infestation %>%
  pomp(times="day",t0=0,
       rprocess=euler(sir_step, delta.t=1),
       rinit=sir_init,
       dmeasure=dmeas,
       rmeasure=rmeas,
       statenames=c("S", "E", "I", "H", "R", "D"),
       paramnames=c("logit_Beta", "logit_phi", "logit_psi", 
                    "logit_gamma_one", "logit_gamma_two", "logit_theta_one", "logit_theta_two",
                    "logit_eta",
                    "sample_size_RNA", "sample_size_Ser",
                    "w_RNA_S", "w_RNA_R", 
                    "w_RNA_E", "w_RNA_I", "w_RNA_H",
                    "w_Ser_S", "w_Ser_E",
                    "w_Ser_I", "w_Ser_H", "w_Ser_R",
                    "logit_prob_Penn_H", "logit_prob_Penn_R", "logit_prob_Penn_D"),
       dprior=covid_pomp.dprior
  ) -> covid_pomp

# Simulate best parameter set
covid_pomp %>%
  simulate(params=c(logit_Beta=posterior_logit_Beta, 
                    logit_phi=posterior_logit_phi, 
                    logit_psi=posterior_logit_psi, 
                    logit_gamma_one=posterior_logit_gamma_one, 
                    logit_gamma_two=posterior_logit_gamma_two, 
                    logit_theta_one=posterior_logit_theta_one, 
                    logit_theta_two=posterior_logit_theta_two,
                    logit_eta=posterior_logit_eta,
                    sample_size_RNA=25, sample_size_Ser=50,
                    w_RNA_S=posterior_w_RNA_S, 
                    w_RNA_R=posterior_w_RNA_R, 
                    w_RNA_E=posterior_w_RNA_E,
                    w_RNA_I=posterior_w_RNA_I, 
                    w_RNA_H=posterior_w_RNA_H,
                    w_Ser_S=posterior_w_Ser_S, 
                    w_Ser_E=posterior_w_Ser_E, 
                    w_Ser_I=posterior_w_Ser_I, 
                    w_Ser_H=posterior_w_Ser_H, 
                    w_Ser_R=posterior_w_Ser_R,
                    logit_prob_Penn_H=posterior_logit_prob_Penn_H,
                    logit_prob_Penn_R=posterior_logit_prob_Penn_R, 
                    logit_prob_Penn_D=posterior_logit_prob_Penn_D,
                    N=10000),
           nsim=1,
           format="data.frame", 
           include.data = TRUE) -> posterior_sims

# Simulate true parameters
covid_pomp %>%
  simulate(params=c(logit_Beta=true_logit_Beta, 
                    logit_phi=true_logit_phi, 
                    logit_psi=true_logit_psi, 
                    logit_gamma_one=true_logit_gamma_one, 
                    logit_gamma_two=true_logit_gamma_two, 
                    logit_theta_one=true_logit_theta_one, 
                    logit_theta_two=true_logit_theta_two,
                    logit_eta=true_logit_eta,
                    sample_size_RNA=25, sample_size_Ser=50,
                    w_RNA_S=true_w_RNA_S, 
                    w_RNA_R=true_w_RNA_R, 
                    w_RNA_E=true_w_RNA_E,
                    w_RNA_I=true_w_RNA_I, 
                    w_RNA_H=true_w_RNA_H,
                    w_Ser_S=true_w_Ser_S, 
                    w_Ser_E=true_w_Ser_E, 
                    w_Ser_I=true_w_Ser_I, 
                    w_Ser_H=true_w_Ser_H, 
                    w_Ser_R=true_w_Ser_R,
                    logit_prob_Penn_H=true_logit_prob_Penn_H,
                    logit_prob_Penn_R=true_logit_prob_Penn_R, 
                    logit_prob_Penn_D=true_logit_prob_Penn_D,
                    N=10000),
           nsim=1,
           format="data.frame", 
           include.data = TRUE) -> true_sims

# Plot the MCMC results for each parameter, as well as the four plots for the real and posterior showing dynamics
pdf(paste0("~/Philly_Covid/pomp/results/traces/traces.pdf"), width=20, height=20)
par(mfrow=c(4,4))

for (type_dynamics in c("true", "posterior")) {
  if (type_dynamics == "true") {
    sims <- true_sims
  } else {
    sims <- posterior_sims
  }
  
  # Plot epidemic dynamics -------------------------------------------------------
  for (i in 1:length(unique(sims$.id))) {
    if (as.character(unique(sims$.id)[i] != "data")) {
      sim <- sims[which(sims$.id == unique(sims$.id)[i]),]
      if (i == 2) {
        plot(sim$day, sim$I, ylim=c(0,10000), type="l", col="red",
             main="Philly COVID-19 dynamics", ylab="# in compartment", xlab="day")
        lines(sim$day, sim$R, col="blue")
        lines(sim$day, sim$S, col="black")
        lines(sim$day, sim$E, col="green")
        lines(sim$day, sim$H, col="yellow")
        lines(sim$day, sim$D, col="purple")
      } else {
        # Need to add code to plot subsequent simulations if more than one
      }
    }
  }
  
  # Plot testing dynamics --------------------------------------------------------
  for (i in 1:length(unique(sims$.id))) {
    if (as.character(unique(sims$.id)[i] != "data")) {
      sim <- sims[which(sims$.id == unique(sims$.id)[i]),]
      if (i == 2) {
        # RNA data plot ----------------------------------------------------
        RNA_data <- do.call(rbind, list("neg_RNA"=sim$neg_RNA, 
                                        "pos_RNA_E"=sim$pos_RNA_E, 
                                        "pos_RNA_I"=sim$pos_RNA_I, 
                                        "pos_RNA_H"=sim$pos_RNA_H))
        colnames(RNA_data) = as.character(sim$day)
        barplot(RNA_data, 
                col=c("grey","green","red","blue"), 
                border="white", 
                space=0.04, 
                font.axis=2, 
                xlab="day",
                ylab="# tests",
                main="RNA data",
                legend=T,
                args.legend = list(x='bottomright'))
        
        # Ser data plot ----------------------------------------------------
        Ser_data <- do.call(rbind, list("neg_Ser"=sim$neg_Ser, 
                                        "pos_Ser_I"=sim$pos_Ser_I, 
                                        "pos_Ser_H"=sim$pos_Ser_H, 
                                        "pos_Ser_R"=sim$pos_Ser_R))
        colnames(Ser_data) <- as.character(sim$day)
        barplot(Ser_data, 
                col=c("grey","red","blue","purple"), 
                border="white", 
                space=0.04, 
                font.axis=2, 
                xlab="day",
                ylab="# tests",
                main="Serology data",
                legend=T)
        
        # Penn EHR ---------------------------------------------------------
        EHR_data <- do.call(rbind, list("reports_Penn_H"=sim$reports_Penn_H,
                                        "reports_Penn_R"=sim$reports_Penn_R,
                                        "reports_Penn_D"=sim$reports_Penn_D))
        colnames(EHR_data) <- as.character(sim$day)
        barplot(EHR_data, 
                col=c("red","blue","black") , 
                border="white", 
                font.axis=2, 
                beside=T,
                ylim=c(0, max(sim$reports_Penn_H, sim$reports_Penn_R, sim$reports_Penn_D)),
                legend=rownames(EHR_data), 
                xlab="day",
                font.lab=2,
                args.legend = list(x='topleft'))
      } else {
        # Need to add code to plot subsequent simulations if more than one
      }
    }
  }
}

# Plot MCMC traces -------------------------------------------------------------
plot(1:nrow(pmcmc_res), inv.logit(pmcmc_res$logit_Beta), type="l", xlab="iteration", ylab="Beta", ylim=c(0, max(inv.logit(pmcmc_res$logit_Beta))))
abline(h = inv.logit(true_logit_Beta), col="red")
plot(1:nrow(pmcmc_res), inv.logit(pmcmc_res$logit_phi), type="l", xlab="iteration", ylab="phi", ylim=c(0, max(inv.logit(pmcmc_res$logit_phi))))
abline(h = inv.logit(true_logit_phi), col="red")
plot(1:nrow(pmcmc_res), inv.logit(pmcmc_res$logit_psi), type="l", xlab="iteration", ylab="psi", ylim=c(0, max(inv.logit(pmcmc_res$logit_psi))))
abline(h = inv.logit(true_logit_psi), col="red")
plot(1:nrow(pmcmc_res), inv.logit(pmcmc_res$logit_gamma_one), type="l", xlab="iteration", ylab="gamma_one", ylim=c(0, max(inv.logit(pmcmc_res$logit_gamma_one))))
abline(h = inv.logit(true_logit_gamma_one), col="red")
plot(1:nrow(pmcmc_res), inv.logit(pmcmc_res$logit_gamma_two), type="l", xlab="iteration", ylab="gamma_two", ylim=c(0, max(inv.logit(pmcmc_res$logit_gamma_two))))
abline(h = inv.logit(true_logit_gamma_two), col="red")
plot(1:nrow(pmcmc_res), inv.logit(pmcmc_res$logit_theta_one), type="l", xlab="iteration", ylab="theta_one", ylim=c(0, max(inv.logit(pmcmc_res$logit_theta_one))))
abline(h = inv.logit(true_logit_theta_one), col="red")
plot(1:nrow(pmcmc_res), inv.logit(pmcmc_res$logit_theta_two), type="l", xlab="iteration", ylab="theta_two", ylim=c(0, max(inv.logit(pmcmc_res$logit_theta_two))))
abline(h = inv.logit(true_logit_theta_two), col="red")

plot(1:nrow(pmcmc_res), pmcmc_res$w_RNA_S, type="l", xlab="iteration", ylab="w_RNA_S", ylim=c(0, max(pmcmc_res$w_RNA_S)))
abline(h = true_w_RNA_S, col="red")
plot(1:nrow(pmcmc_res), pmcmc_res$w_RNA_E, type="l", xlab="iteration", ylab="w_RNA_E", ylim=c(0, max(pmcmc_res$w_RNA_E)))
abline(h = true_w_RNA_E, col="red")
plot(1:nrow(pmcmc_res), pmcmc_res$w_RNA_I, type="l", xlab="iteration", ylab="w_RNA_I", ylim=c(0, max(pmcmc_res$w_RNA_I)))
abline(h = true_w_RNA_I, col="red")
plot(1:nrow(pmcmc_res), pmcmc_res$w_RNA_H, type="l", xlab="iteration", ylab="w_RNA_H", ylim=c(0, max(pmcmc_res$w_RNA_H)))
abline(h = true_w_RNA_H, col="red")
plot(1:nrow(pmcmc_res), pmcmc_res$w_RNA_R, type="l", xlab="iteration", ylab="w_RNA_R", ylim=c(0, max(pmcmc_res$w_RNA_R)))
abline(h = true_w_RNA_R, col="red")

plot(1:nrow(pmcmc_res), pmcmc_res$w_Ser_S, type="l", xlab="iteration", ylab="w_Ser_S", ylim=c(0, max(pmcmc_res$w_Ser_S)))
abline(h = true_w_Ser_S, col="red")
plot(1:nrow(pmcmc_res), pmcmc_res$w_Ser_E, type="l", xlab="iteration", ylab="w_Ser_E", ylim=c(0, max(pmcmc_res$w_Ser_E)))
abline(h = true_w_Ser_E, col="red")
plot(1:nrow(pmcmc_res), pmcmc_res$w_Ser_I, type="l", xlab="iteration", ylab="w_Ser_I", ylim=c(0, max(pmcmc_res$w_Ser_I)))
abline(h = true_w_Ser_I, col="red")
plot(1:nrow(pmcmc_res), pmcmc_res$w_Ser_H, type="l", xlab="iteration", ylab="w_Ser_H", ylim=c(0, max(pmcmc_res$w_Ser_H)))
abline(h = true_w_Ser_H, col="red")
plot(1:nrow(pmcmc_res), pmcmc_res$w_Ser_R, type="l", xlab="iteration", ylab="w_Ser_R", ylim=c(0, max(pmcmc_res$w_Ser_R)))
abline(h = true_w_Ser_R, col="red")

plot(1:nrow(pmcmc_res), inv.logit(pmcmc_res$logit_prob_Penn_H), type="l", xlab="iteration", ylab="prob_Penn_H", ylim=c(0, max(inv.logit(pmcmc_res$logit_prob_Penn_H))))
abline(h = inv.logit(true_logit_prob_Penn_H), col="red")
plot(1:nrow(pmcmc_res), inv.logit(pmcmc_res$logit_prob_Penn_R), type="l", xlab="iteration", ylab="prob_Penn_R", ylim=c(0, max(inv.logit(pmcmc_res$logit_prob_Penn_R))))
abline(h = inv.logit(true_logit_prob_Penn_R), col="red")
plot(1:nrow(pmcmc_res), inv.logit(pmcmc_res$logit_prob_Penn_D), type="l", xlab="iteration", ylab="prob_Penn_D", ylim=c(0, max(inv.logit(pmcmc_res$logit_prob_Penn_D))))
abline(h = inv.logit(true_logit_prob_Penn_D), col="red")

dev.off()



"""# Outdated code blocks
- Outdated observation model (removed 5-18-20)
- Outdated likelihood model (removed 5-18-20)
"""

# Outdated observation model ---------------------------------------------------
rmeas <- function (S, E, I, H, R, D, N,
                   sample_size_RNA, sample_size_Ser,
                   w_RNA_S, w_RNA_R,
                   w_RNA_E, w_RNA_I, w_RNA_H,
                   w_Ser_S, w_Ser_E,
                   w_Ser_I, w_Ser_H, w_Ser_R,
                   prob_Penn_H, prob_Penn_R, prob_Penn_D, 
                   ...) {
  # RT-PCR daily sample --------------------------------------------------------
  ## Take latent sample from weighted population -------------------------------
  pop_RNA <- c(rep("S", S * w_RNA_S), rep("E", E * w_RNA_E),
               rep("I", I * w_RNA_I), rep("H", H * w_RNA_H), 
               rep("R", R * w_RNA_R))
  latent_sample_RNA <- as.vector(pop_RNA[sample(length(pop_RNA), sample_size_RNA)])
  
  ## Construction of pos. and neg. RNA samples ---------------------------------
  neg_RNA = length(which(latent_sample_RNA == "S")) + length(which(latent_sample_RNA == "R"))
  pos_RNA_E = length(which(latent_sample_RNA == "E"))
  pos_RNA_I = length(which(latent_sample_RNA == "I"))
  pos_RNA_H = length(which(latent_sample_RNA == "H"))

  # Serology daily sample ------------------------------------------------------
  ## Take latent sample from weighted population -------------------------------
  pop_Ser <- c(rep("S", S * w_Ser_S), rep("E", E * w_Ser_E), 
               rep("I", I * w_Ser_I), rep("H", H * w_Ser_H), 
               rep("R", R * w_Ser_R))
  latent_sample_Ser <- as.vector(pop_Ser[sample(length(pop_Ser), sample_size_Ser)])
  
  ## Construction of pos. and neg. serology samples ----------------------------
  neg_Ser = length(which(latent_sample_Ser == "S")) + length(which(latent_sample_Ser == "E"))
  pos_Ser_I = length(which(latent_sample_Ser == "I"))
  pos_Ser_H = length(which(latent_sample_Ser == "H"))
  pos_Ser_R = length(which(latent_sample_Ser == "R"))
  
  # Penn EHR daily sample ------------------------------------------------------
  reports_Penn_H = rbinom(n=1, H, prob_Penn_H)
  reports_Penn_R = rbinom(n=1, R, prob_Penn_R)
  reports_Penn_D = rbinom(n=1, D, prob_Penn_D)

  # Return all observations of the epidemic ------------------------------------
  c(neg_RNA=neg_RNA, pos_RNA_E=pos_RNA_E, pos_RNA_I=pos_RNA_I, pos_RNA_H=pos_RNA_H, 
    neg_Ser=neg_Ser, pos_Ser_I=pos_Ser_I, pos_Ser_H=pos_Ser_H, pos_Ser_R=pos_Ser_R,
    reports_Penn_H=reports_Penn_H, reports_Penn_R=reports_Penn_R, reports_Penn_D=reports_Penn_D)
}

# Outdated likelihood model ----------------------------------------------------
dmeas <- function (S, E, I, H, R, D,
                   sample_size_RNA, sample_size_Ser,
                   w_RNA_S, w_RNA_R,
                   w_RNA_E, w_RNA_I, w_RNA_H,
                   w_Ser_S, w_Ser_E, 
                   w_Ser_I, w_Ser_H, w_Ser_R,
                   prob_Penn_H, prob_Penn_R, prob_Penn_D,
                   neg_RNA, pos_RNA_E, pos_RNA_I, pos_RNA_H, 
                   neg_Ser, pos_Ser_I, pos_Ser_H, pos_Ser_R,
                   reports_Penn_H, reports_Penn_R, reports_Penn_D,
                   log,
                   ...) {
  # RT-PCR likelihoods ---------------------------------------------------------
  ## Get sample distribution for each compartment ------------------------------
  pop <- c(rep("S", S * w_RNA_S), rep("E", E * w_RNA_E), rep("I", I * w_RNA_I), 
           rep("H", H * w_RNA_H), rep("R", R * w_RNA_R))
  neg_RNA_samps <- vector()
  pos_RNA_E_samps <- vector()
  pos_RNA_I_samps <- vector()
  pos_RNA_H_samps <- vector()
  get_dists <- sapply(1:10000, function(x) {
    latent_sample_RNA <- as.vector(pop[sample(length(pop), sample_size_RNA)])
    neg_RNA_samps <<- c(neg_RNA_samps, length(which(latent_sample_RNA == "S")) + length(which(latent_sample_RNA == "R")))
    pos_RNA_E_samps <<- c(pos_RNA_E_samps, length(which(latent_sample_RNA == "E")))
    pos_RNA_I_samps <<- c(pos_RNA_I_samps, length(which(latent_sample_RNA == "I")))
    pos_RNA_H_samps <<- c(pos_RNA_H_samps, length(which(latent_sample_RNA == "H")))
  })
  neg_RNA_samp_dist <- hist(neg_RNA_samps, breaks=seq(min(neg_RNA_samps) - 0.5, max(neg_RNA_samps) + 0.5, by=1), freq=F, plot=F)
  pos_RNA_E_samp_dist <- hist(pos_RNA_E_samps, breaks=seq(min(pos_RNA_E_samps) - 0.5, max(pos_RNA_E_samps) + 0.5, by=1), freq=F, plot=F)
  pos_RNA_I_samp_dist <- hist(pos_RNA_I_samps, breaks=seq(min(pos_RNA_I_samps) - 0.5, max(pos_RNA_I_samps) + 0.5, by=1), freq=F, plot=F)
  pos_RNA_H_samp_dist <- hist(pos_RNA_H_samps, breaks=seq(min(pos_RNA_H_samps) - 0.5, max(pos_RNA_H_samps) + 0.5, by=1), freq=F, plot=F)
  ## Get log likelihoods based on sampling distributions -----------------------
  dens_neg_RNA <- neg_RNA_samp_dist$density[which(neg_RNA_samp_dist$mids == neg_RNA)]
  log_lik_neg_RNA <- ifelse(length(dens_neg_RNA) == 0, 0, log(dens_neg_RNA))
  dens_pos_RNA_E <- pos_RNA_E_samp_dist$density[which(pos_RNA_E_samp_dist$mids == pos_RNA_E)]
  log_lik_pos_RNA_E <- ifelse(length(dens_pos_RNA_E) == 0, 0, log(dens_pos_RNA_E))
  dens_pos_RNA_I <- pos_RNA_I_samp_dist$density[which(pos_RNA_I_samp_dist$mids == pos_RNA_I)]
  log_lik_pos_RNA_I <- ifelse(length(dens_pos_RNA_I) == 0, 0, log(dens_pos_RNA_I)) 
  dens_pos_RNA_H <- pos_RNA_H_samp_dist$density[which(pos_RNA_H_samp_dist$mids == pos_RNA_H)]
  log_lik_pos_RNA_H <- ifelse(length(dens_pos_RNA_H) == 0, 0, log(dens_pos_RNA_H)) 

  # Serology likelihoods -------------------------------------------------------
  ## Get sample distribution for each compartment ------------------------------
  pop <- c(rep("S", S * w_Ser_S), rep("E", E * w_Ser_E), rep("I", I * w_Ser_I), 
           rep("H", H * w_Ser_H), rep("R", R * w_Ser_R))
  neg_Ser_samps <- vector()
  pos_Ser_I_samps <- vector()
  pos_Ser_H_samps <- vector()
  pos_Ser_R_samps <- vector()
  get_dists <- sapply(1:10000, function(x) {
    latent_sample_Ser <- as.vector(pop[sample(length(pop), sample_size_Ser)])
    neg_Ser_samps <<- c(neg_Ser_samps, length(which(latent_sample_Ser == "S")) + length(which(latent_sample_Ser == "E")))
    pos_Ser_I_samps <<- c(pos_Ser_I_samps, length(which(latent_sample_Ser == "I")))
    pos_Ser_H_samps <<- c(pos_Ser_H_samps, length(which(latent_sample_Ser == "H")))
    pos_Ser_R_samps <<- c(pos_Ser_R_samps, length(which(latent_sample_Ser == "R")))
  })
  neg_Ser_samp_dist <- hist(neg_Ser_samps, breaks=seq(min(neg_Ser_samps) - 0.5, max(neg_Ser_samps) + 0.5, by=1), freq=F, plot=F)
  pos_Ser_I_samp_dist <- hist(pos_Ser_I_samps, breaks=seq(min(pos_Ser_I_samps) - 0.5, max(pos_Ser_I_samps) + 0.5, by=1), freq=F, plot=F)
  pos_Ser_H_samp_dist <- hist(pos_Ser_H_samps, breaks=seq(min(pos_Ser_H_samps) - 0.5, max(pos_Ser_H_samps) + 0.5, by=1), freq=F, plot=F)
  pos_Ser_R_samp_dist <- hist(pos_Ser_R_samps, breaks=seq(min(pos_Ser_R_samps) - 0.5, max(pos_Ser_R_samps) + 0.5, by=1), freq=F, plot=F)
  ## Get log likelihoods based on sampling distributions -----------------------
  dens_neg_Ser <- neg_Ser_samp_dist$density[which(neg_Ser_samp_dist$mids == neg_Ser)]
  log_lik_neg_Ser <- ifelse(length(dens_neg_Ser) == 0, 0, log(dens_neg_Ser))
  dens_pos_Ser_I <- pos_Ser_I_samp_dist$density[which(pos_Ser_I_samp_dist$mids == pos_Ser_I)]
  log_lik_pos_Ser_I <- ifelse(length(dens_pos_Ser_I) == 0, 0, log(dens_pos_Ser_I)) 
  dens_pos_Ser_H <- pos_Ser_H_samp_dist$density[which(pos_Ser_H_samp_dist$mids == pos_Ser_H)]
  log_lik_pos_Ser_H <- ifelse(length(dens_pos_Ser_H) == 0, 0, log(dens_pos_Ser_H)) 
  dens_pos_Ser_R <- pos_Ser_R_samp_dist$density[which(pos_Ser_R_samp_dist$mids == pos_Ser_R)]
  log_lik_pos_Ser_R <- ifelse(length(dens_pos_Ser_R) == 0, 0, log(dens_pos_Ser_R))

  # Penn EHR likelihoods -------------------------------------------------------
  log_lik_Penn_H <- dbinom(x=reports_Penn_H, size=H, prob=prob_Penn_H, log=log)
  log_lik_Penn_R <- dbinom(x=reports_Penn_R, size=R, prob=prob_Penn_R, log=log)
  log_lik_Penn_D <- dbinom(x=reports_Penn_D, size=D, prob=prob_Penn_D, log=log)

  # Combine the log likelihoods into combined log likelihood -------------------
  combined_log_lik <- log_lik_neg_RNA + log_lik_pos_RNA_E + log_lik_pos_RNA_I + log_lik_pos_RNA_H +
                      log_lik_neg_Ser + log_lik_pos_Ser_I + log_lik_pos_Ser_H + log_lik_pos_Ser_R +
                      log_lik_Penn_H + log_lik_Penn_R + log_lik_Penn_D
  
  # Return combined log likelihood ---------------------------------------------
  combined_log_lik
}
